### ISSUE TITLE
What was the purpose of this fork?

### ISSUE THREAD

**Issue by danshome** [melloware/commons-beanutils2#30]
I found this fork from https://issues.apache.org/jira/projects/BEANUTILS/issues/BEANUTILS-532, but it wasn't clear if this was created as a stop-gap to address security issues or for some other reason.  I also noticed that the README.md on https://github.com/apache/commons-beanutils is now referencing that commons-beanutils2@2.0.0 can be downloaded from Maven Central but the only release I can find in Maven Central is a release from this fork.   Do you happen to have any insight into if org.apache.commons:commons-beanutils2:2.0.0 is about to be released?

**Comment by danshome** [comment]
It looks like @garydgregory has been making a LOT of changes recently, even today in commons-beanutils and all the other commons projects.  Do you know if they are about to release 2.0.0?  I see you are a committer on that project is the only reason I ask.  Thanks for the information.

**Comment by melloware** [comment]
If you look over the history and on the mailing lists I have been asking for over 3 years for a release. I finally gave up and thus this fork.  Gary definitely makes commits and merges PRs but no release in sight.
